In [3]:
import pandas as pd
import time
from urllib.parse import urlencode

base_url = "https://data.cityofnewyork.us/resource/bkfu-528j.json"
limit = 50000
offset = 0
all_data = []

# Build proper query parameters
where_clause = "start_date_time >= '2021-01-01T00:00:00' AND event_borough = 'Queens'"

params = {
    "$limit": limit,
    "$offset": offset,
    "$where": where_clause
}

print("üöÄ Starting filtered download (2021+ in Queens)...")

while True:
    print(f"üì¶ Fetching records {offset} to {offset + limit}...")
    try:
        # Encode query string safely
        query_string = urlencode(params)
        url = f"{base_url}?{query_string}"
        batch = pd.read_json(url)

        if batch.empty:
            print("‚úÖ No more data. Stopping.")
            break

        all_data.append(batch)
        offset += limit
        params["$offset"] = offset
        time.sleep(1)

    except Exception as e:
        print(f"‚ö†Ô∏è Error at offset {offset}: {str(e)}")
        break

if all_data:
    df_all = pd.concat(all_data, ignore_index=True)
    print(f"üéâ Finished. Total rows downloaded: {len(df_all)}")
else:
    print("‚ùå No data downloaded.")

üöÄ Starting filtered download (2021+ in Queens)...
üì¶ Fetching records 0 to 50000...
üì¶ Fetching records 50000 to 100000...
üì¶ Fetching records 100000 to 150000...
üì¶ Fetching records 150000 to 200000...
üì¶ Fetching records 200000 to 250000...
üì¶ Fetching records 250000 to 300000...
üì¶ Fetching records 300000 to 350000...
üì¶ Fetching records 350000 to 400000...
üì¶ Fetching records 400000 to 450000...
üì¶ Fetching records 450000 to 500000...
üì¶ Fetching records 500000 to 550000...
üì¶ Fetching records 550000 to 600000...
üì¶ Fetching records 600000 to 650000...
üì¶ Fetching records 650000 to 700000...
üì¶ Fetching records 700000 to 750000...
üì¶ Fetching records 750000 to 800000...
üì¶ Fetching records 800000 to 850000...
üì¶ Fetching records 850000 to 900000...
üì¶ Fetching records 900000 to 950000...
üì¶ Fetching records 950000 to 1000000...
üì¶ Fetching records 1000000 to 1050000...
üì¶ Fetching records 1050000 to 1100000...
üì¶ Fetching records 1100000 to 1150000...
üì¶ Fetching records 1150000 to 1200000...
üì¶ Fetching records 1200000 to 1250000...
üì¶ Fetching records 1250000 to 1300000...
üì¶ Fetching records 1300000 to 1350000...
üì¶ Fetching records 1350000 to 1400000...
üì¶ Fetching records 1400000 to 1450000...
üì¶ Fetching records 1450000 to 1500000...
üì¶ Fetching records 1500000 to 1550000...
üì¶ Fetching records 1550000 to 1600000...
üì¶ Fetching records 1600000 to 1650000...
üì¶ Fetching records 1650000 to 1700000...
üì¶ Fetching records 1700000 to 1750000...
üì¶ Fetching records 1750000 to 1800000...
üì¶ Fetching records 1800000 to 1850000...
üì¶ Fetching records 1850000 to 1900000...
üì¶ Fetching records 1900000 to 1950000...
üì¶ Fetching records 1950000 to 2000000...
üì¶ Fetching records 2000000 to 2050000...
üì¶ Fetching records 2050000 to 2100000...
üì¶ Fetching records 2100000 to 2150000...
üì¶ Fetching records 2150000 to 2200000...
üì¶ Fetching records 2200000 to 2250000...
üì¶ Fetching records 2250000 to 2300000...
üì¶ Fetching records 2300000 to 2350000...
üì¶ Fetching records 2350000 to 2400000...
üì¶ Fetching records 2400000 to 2450000...
üì¶ Fetching records 2450000 to 2500000...
üì¶ Fetching records 2500000 to 2550000...
üì¶ Fetching records 2550000 to 2600000...
üì¶ Fetching records 2600000 to 2650000...
üì¶ Fetching records 2650000 to 2700000...
üì¶ Fetching records 2700000 to 2750000...
üì¶ Fetching records 2750000 to 2800000...
üì¶ Fetching records 2800000 to 2850000...
üì¶ Fetching records 2850000 to 2900000...
üì¶ Fetching records 2900000 to 2950000...
üì¶ Fetching records 2950000 to 3000000...
üì¶ Fetching records 3000000 to 3050000...
üì¶ Fetching records 3050000 to 3100000...
üì¶ Fetching records 3100000 to 3150000...
üì¶ Fetching records 3150000 to 3200000...
üì¶ Fetching records 3200000 to 3250000...
üì¶ Fetching records 3250000 to 3300000...
üì¶ Fetching records 3300000 to 3350000...
üì¶ Fetching records 3350000 to 3400000...
üì¶ Fetching records 3400000 to 3450000...
üì¶ Fetching records 3450000 to 3500000...
üì¶ Fetching records 3500000 to 3550000...
üì¶ Fetching records 3550000 to 3600000...
üì¶ Fetching records 3600000 to 3650000...
üì¶ Fetching records 3650000 to 3700000...
üì¶ Fetching records 3700000 to 3750000...
üì¶ Fetching records 3750000 to 3800000...
üì¶ Fetching records 3800000 to 3850000...
üì¶ Fetching records 3850000 to 3900000...
üì¶ Fetching records 3900000 to 3950000...
üì¶ Fetching records 3950000 to 4000000...
üì¶ Fetching records 4000000 to 4050000...
üì¶ Fetching records 4050000 to 4100000...
üì¶ Fetching records 4100000 to 4150000...
‚úÖ No more data. Stopping.
üéâ Finished. Total rows downloaded: 4090024

In [7]:
df_all['time'] = pd.to_datetime(df_all['start_date_time'])
df_all['year'] = df_all['time'].dt.year
df_all['year'].unique()

array([2024, 2025, 2021, 2022, 2023], dtype=int32)

In [14]:
df_all.to_csv('events_data.csv', index=False)

In [83]:
df_copy = df_all.copy()

In [84]:
df_copy.head()

,event_id,event_name,start_date_time,end_date_time,event_agency,event_type,event_borough,event_location,street_closure_type,community_board,police_precinct,event_street_side,time,year
0,792821,Football - Youth,2024-09-14 08:00:00,2024-09-14 20:00:00,Parks Department,Sport - Youth,Queens,Rockaway Beach Boardwalk: Football-01,N/A,"14,","101,",NaN,2024-09-14 08:00:00,2024
1,761335,Kindness Carnival,2024-10-05 12:00:00,2024-10-05 17:00:00,Parks Department,Special Event,Queens,Cambria Playground/Cabbell Park: Lawn,N/A,"13,","105,",NaN,2024-10-05 12:00:00,2024
2,770618,Picnic,2024-09-15 11:00:00,2024-09-15 16:00:00,Parks Department,Special Event,Queens,"Cunningham Park: Picnic Green 2 ,Cunningham ...",N/A,"08, 8,","107,",NaN,2024-09-15 11:00:00,2024
3,792381,Soccer - Non Regulation,2024-10-17 17:00:00,2024-10-17 20:00:00,Parks Department,Sport - Youth,Queens,Flushing Meadows Corona Park: Soccer-01,N/A,"81,","110,",NaN,2024-10-17 17:00:00,2024
4,780647,Softball (Little league),2024-09-24 15:30:00,2024-09-24 19:00:00,Parks Department,Sport - Youth,Queens,Kissena Corridor West: Captain Mario Fajardo P...,N/A,"07,","109,",NaN,2024-09-24 15:30:00,2024

In [85]:
df_copy.isna().sum()

event_id                     0
event_name                   0
start_date_time              0
end_date_time                0
event_agency                 0
event_type                   0
event_borough                0
event_location               0
street_closure_type          0
community_board              0
police_precinct              0
event_street_side      4029625
time                         0
year                         0
dtype: int64

In [86]:
df_copy = df_copy.drop('event_street_side', axis=1)

In [87]:
df_copy.isna().sum()

event_id               0
event_name             0
start_date_time        0
end_date_time          0
event_agency           0
event_type             0
event_borough          0
event_location         0
street_closure_type    0
community_board        0
police_precinct        0
time                   0
year                   0
dtype: int64

In [88]:
df_copy.columns

Index(['event_id', 'event_name', 'start_date_time', 'end_date_time',
       'event_agency', 'event_type', 'event_borough', 'event_location',
       'street_closure_type', 'community_board', 'police_precinct', 'time',
       'year'],
      dtype='object')

In [89]:
df_copy['community_board'].unique()

array(['14,', '13,', '08, 8,', '81,', '07,', '05,', '82,', '02, 05,',
       '11,', '08,', '03, 04, 3,', '01,', '12,', '1,', '3,', '01, 1,',
       '5,', '02,', '07, 08, 10, 12,', '10,', '05, 81,', '11, 81,', '4,',
       '7,', '2,', '03,', '8,', '01, 02,', '05, 5,', '3, 4, 6, 7, 8,',
       '06,', '01, 02, 05,', '07, 81,', '05, 07, 08, 10, 82,',
       '05, 07, 1, 11,', '11, 13,', '07, 7,', '12, 82,', '10, 82,',
       '07, 82,', '10, 12, 5,', '07, 11,', '04,', '12, 13,', '05, 12,',
       '08, 11,', '05, 08, 10, 82,', '09,', '5, 6, 9,', '14, 84,',
       '09, 9,', '02, 5,', '6,', '3, 4,', '07, 08,', '07, 10, 82,',
       '05, 08,', '10, 5,', '9,', '01, 2,', '07, 10,', '01, ', '12, ',
       '2, ', '07, ', '1, ', '07, 11, ', '82, ', '81, ', '02, ', '6, ',
       '4, ', '3, ', '7, ', '01, 08, ', '11, ', '5, ', '10, ', '13, ',
       '14, ', '05, ', '2, 3, 4, ', '8, ', '9, ', '5, 6, 9, ',
       '3, 4, 6, 7, 8, 81, ', '3, 4, ', '08, ', '07, 11, 81, ',
       '03, 04, 81, ', '05, 10, ', '11, 13, ', '07, 81, ', '07, 08, 11, ',
       '03, ', '05, 08, ', '07, 10, 81, ', '08, 81, ', '08, 11, ',
       '10, 82, ', '05, 08, 10, 12, 82, ', '05, 08, 82, ', '13, 14, 81, ',
       '07, 08, 11, 12, ', '02, 5, 81, ', '03, 81, ', '08, 13, ',
       '03, 07, ', '01, 02, 03, 05, 07, 08, 09, 1, 10, 12, 13, 81, 82, ',
       '01, 08, 12, ', '05, 5, ', '2, 3, ', '12, 13, ', '07, 14, ',
       '3, 4, 6, 7, 8, ', '05, 08, 12, ', '05, 11, ', '10, 12, 13, ',
       '05, 07, 11, ', '08, 13, 14, 81, ', '12, 8, ',
       '05, 07, 08, 10, 13, 81, ', '08, 11, 12, ', '05, 07, 11, 12, 13, ',
       '03, 04, ', '10, 9,', '05, 07, 08, ', '08, 82, ',
       '05, 08, 10, 13, 82, ', '1, 5, ', '01, 81, ', '09, ', '05, 1, ',
       '04, ', '07, 08, 81, ', '05, 82, ', '07, 08, ',
       '01, 02, 03, 05, 07, 08, 09, 1, 10, 12, 5, 81, 82, ', '14, 81, ',
       '04, 05, ', '1, 2, ', '01, 2, ', '07, 3, 4, 6, 7, 8, ', '5, 82, ',
       '11, 7, ', '06, 6, ', '07, 7, ', '06, 09, ', '08, 8, 81, ',
       '07, 12, 81, ', '06, ', '07, 08, 12, 81, ', '05, 81, ', '07, 1, ',
       '4, 5, ', '01, 05, ', '03, 3, ', '01, 1, ', '08, 8, ', '2, 4, ',
       '01, 07, ', '02, 1, 5, ', '09, 9, ', '11, 8, 82, 9, ', '10, 9, ',
       '5, 81, 82, ', '07, 11, 81, 82, ', '02, 05, ', '07, 08, 10, 12, ',
       '5, 6, 82, 9, ', '05, 12, ', '07, 10, 82, ', '05, 07, 08, 82, ',
       '07, 08, 13, 81, ', '11, 12, ', '01, 5, ', '05, 07, 08, 81, ',
       '08, 10, ', '07, 5, 81, ', '14, 84, ', '07, 08, 13, 81,',
       '03, 04,', '05, 08, 82,', '03, 04, 81,', '07, 11, 81, 82,',
       '07, 11, 81,', '05, 07, 08, 82,', '1, 2,', '08, 10,', '01, 5,',
       '03, 3,', '5, 81, 82,', '11, 12,', '2, 3, 4,', '07, 5, 81,',
       '4, 5,', '12, 8,', '08, 13,', '01, 07, 08, 1, 10, 12, 5, 81, 82,',
       '05, 08, 11, 12,', '01, 81,', '11, 7,', '03, 81,', '01, 04,',
       '01, 82,', '12, 8, 9,', '01, 05, 07, 08, 12, 81, 82,',
       '3, 4, 6, 7, 8, 81,', '01, 08,', '6, 8, 81, 9,', '08, 82,',
       '11, 5, 8, 82,', '03, 10,', '10, 5, 82, 9,', '01, 03,', '2, 81,',
       '2, 3,', '02, 5, 81,', '05, 10,',
       '01, 03, 05, 07, 08, 10, 12, 81, 82,', '08, 11, 12, 13,',
       '02, 81,', '08, 81,', '07, 08, 11, 12,', '07, 08, 11,', '5, 6,',
       '05, 08, 10, 12,', '08, 11, 12,', '07, 08, 81,', '05, 07, 08, 13,',
       '1, 3,', '82, 9,', '08, 12,', '05, 08, 10, 13, 82,', '05, 07, 08,',
       '01, 02, 03, 05, 07, 08, 09, 10, 11, 12, 5, 81, 82,',
       '01, 05, 07, 08, 12,', '05, 07, 11, 12, 13,', '10, 13,', '03, 08,',
       '07, 6,', '01, 05, 07, 08, 10, 12, 81, 82,', '07, 11, 12, 13,',
       '01, 03, 05, 07, 08, 09, 10, 12,', '05, 07, 08, 11, 12, 13,',
       '14, 81,', '07, 11, 13, 81,',
       '1, 10, 11, 13, 15, 18, 2, 56, 6, 7, 82, 9,', '04, 4,',
       '01, 03, 05, 07, 08, 09, 10, 12, 82,', '10, 12, 9,', '2, 5,',
       '01, 02, 03, 05, 07, 08, 09, 10, 12, 81, 82,', '5, 82,', '03, 12,',
       '07, 12, 13,', '06, 6,', '1, 2, 5, 6, 64, 8,', '5, 6, 82, 9,',
       '05, 82,', '11, 8, 82, 9,', '1, 11, 13, 2, 3, 4, 5, 6, 7, 8, 81,',
       '5, 81,', '07, 5,', '1, 11, 3, 4, 7, 8, 80, 81,', '05, 08, 11,',
       '08, 11, 13,', '02, 2,', '1, 2, 3, 4, 5, 6, 7, 8, 81,',
       '01, 05, 07, 08, 12, 14, 81, 82,', '11, 5, 6, 8, 82,',
       '07, 3, 4, 6, 7, 8,', '04, 81,', '10, 14, 82, 84, 9,', '10, 12,',
       '5, 6, 8, 81,', '01, 02, 05, 07, 08, 09, 10, 12, 5, 81, 82,',
       '07, 10, 81, 82,', '01, 05, 07, 08, 10, 12, 14, 81, 82,',
       '01, 12,', '05, 07, 81,', '03, 05, 07, 08, 10, 12, 81, 82,',
       '07, 08, 10, 13,', '05, 07, 08, 12,', '05, 13,', '03, 06, 09,',
       '05, 07, 08, 1, 12, 14, 81, 82,', '07, 1, 11, 12,', '04, 3, 81,',
       '03, 06, 09, 11,', '01, 05, 07, 08, 10, 5,', '10, 84,', '13, 82,',
       '1, 10, 11, 13, 2, 5, 56, 6, 7, 8, 82,', '1, 5,', '11, 3, 5,',
       '01, 05,', '05, 07, 08, 1, 12, 81, 82,', '07, 1,', '12, 81,',
       '02, 07,', '07, 08, 1, 5, 81,', '08, 3,', '07, 08, 12, 13, 81,',
       '07, 13,', '12, 3,', '05, 10, 12,', '10, 12, 13,', '10, 81,',
       '11, 12, 6, 8, 81, 9,', '12, 6, 8, 9,', '05, 1, 82,',
       '05, 07, 08, 1, 10, 12, 14, 81, 82,', '3, 4, 81,', '07, 1, 11,',
       '1, 81,', '04, 3,', '05, 07, 08, 11, 13,', '02, 05, 81,',
       '08, 14, 81,', '12, 14, 81,', '08, 9,', '8, 81,', '13, 14,',
       '05, 07, 08, 1, 12,', '2, 4,', '07, 08, 5,', '3, 81,', '07, 3,',
       '12, 13, 8,', '12, 14,', '3, 4, 6,'], dtype=object)

In [90]:
df_copy['police_precinct'].unique()

array(['101,', '105,', '107,', '110,', '109,', '104,', '102,',
       '104, 108,', '100,', '111,', '110, 115,', '114,', '113,', '115,',
       '75,', '108,', '103,', '103, 106, 107, 109,', '106,',
       '104, 110, 75,', '110, 111,', '08,', '108, 114,', '112,',
       '104, 108, 114,', '109, 110,', '102, 104, 106, 107, 109,',
       '104, 109, 111, 114,', '105, 111,', '102, 113,', '102, 106,',
       '102, 109,', '104, 106, 113,', '109, 111,', '105, 113,',
       '100, 101,', '103, 104,', '107, 111,', '102, 104, 106, 107,',
       '104, 110,', '107, 109,', '102, 106, 109,', '103, 113,',
       '104, 107,', '104, 106,', '106, 109,', '114, ', '113, ', '108, ',
       '109, ', '109, 111, ', '102, ', '110, ', '112, ', '103, ', '115, ',
       '107, 114, ', '107, ', '75, ', '106, ', '105, ', '111, ', '100, ',
       '104, ', '108, 110, 115, ', '110, 115, ', '101, ',
       '109, 110, 111, ', '104, 106, ', '105, 111, ', '109, 110, ',
       '107, 109, 111, ', '104, 107, ', '106, 109, 110, ', '107, 110, ',
       '107, 111, ', '102, 106, ', '102, 103, 104, 106, 107, ',
       '102, 104, 107, ', '101, 105, 110, ', '107, 109, 111, 113, ',
       '104, 108, 110, ', '105, 107, ', '08, ', '109, 115, ',
       '102, 103, 104, 105, 106, 107, 108, 109, 110, 113, 114, 115, ',
       '103, 107, 113, 114, ', '108, 115, ', '83, ', '105, 113, ',
       '101, 109, ', '103, 104, 107, ', '104, 111, ',
       '103, 105, 106, 113, ', '104, 109, 111, ', '101, 105, 107, 110, ',
       '103, 107, ', '104, 105, 106, 107, 109, 110, ', '103, 107, 111, ',
       '104, 105, 109, 111, 113, ', '107, 111, 113, ', '104, 107, 109, ',
       '102, 107, ', '102, 104, 105, 106, 107, ', '104, 120, ',
       '110, 114, ', '104, 114, ', '107, 109, 110, ', '102, 104, ',
       '107, 109, ',
       '102, 103, 104, 106, 107, 108, 109, 110, 113, 114, 115, ',
       '101, 110, ', '104, 110, ', '108, 114, ', '102, 112, ',
       '110, 113, 24, ', '107, 109, 110, 113, ', '109, 114, ',
       '104, 83, ', '108, 110, ', '104, 75, ', '104, 108, 114, ',
       '102, 107, 111, ', '102, 104, 110, ', '102, 109, 110, 111, ',
       '104, 108, ', '103, 106, 107, 109, ', '103, 113, ', '102, 75, ',
       '103, 104, ', '102, 106, 109, ', '102, 104, 107, 109, ',
       '105, 107, 109, 110, ', '103, 111, ', '100, 101, ',
       '104, 107, 109, 110, ', '106, 107, ', '104, 109, 110, ',
       '105, 107, 109, 110,', '102, 104, 107,', '102, 109, 110, 111,',
       '104, 75,', '109, 110, 111,', '102, 104, 107, 109,', '106, 107,',
       '104, 114,', '102, 104, 110,', '103, 111,', '108, 110, 115,',
       '104, 109, 110,', '104, 83,', '103, 107,', '105, 107,',
       '103, 105, 113,', '102, 103, 104, 106, 107, 109, 110, 114,',
       '103, 104, 107, 111,', '110, 114,', '102, 114,', '102, 103, 107,',
       '102, 103, 104, 107, 109, 110, 114, 75,', '107, 114,', '102, 107,',
       '102, 104, 107, 111,', '106, 115,', '102, 104, 106,', '114, 115,',
       '106, 113,', '108, 115,', '104, 108, 110,',
       '102, 104, 106, 107, 109, 110, 113, 114, 115,',
       '105, 107, 111, 113,', '108, 110,', '107, 110,',
       '107, 109, 111, 113,', '107, 109, 111,', '104, 112,',
       '103, 104, 106, 107,', '103, 107, 111,', '107, 109, 110,',
       '104, 105, 107, 109,', '107, 113,', '102, 104, 105, 106, 107,',
       '104, 107, 109,',
       '102, 104, 106, 107, 108, 109, 110, 111, 113, 114, 115,',
       '104, 107, 109, 113, 114,', '104, 105, 109, 111, 113,',
       '105, 106,', '107, 115,', '104, 68,', '103, 105,', '109, 112,',
       '105, 109, 111, 113,', '102, 104, 106, 107, 109, 113, 114, 115,',
       '104, 105, 107, 109, 111, 113,', '101, 110,',
       '105, 109, 110, 111,',
       '102, 106, 108, 114, 60, 61, 62, 63, 68, 69, 72, 75, 76, 84, 88, 90, 94,',
       '102, 103, 106,',
       '102, 104, 106, 107, 108, 109, 110, 113, 114, 115,', '102, 104,',
       '103, 115,', '105, 109, 113,', '108, 114, 17, 18, 19, 22,',
       '102, 75,', '83,', '102, 105, 107, 111,',
       '1, 104, 105, 107, 108, 109, 110, 111, 112, 13, 17, 5, 7, 76, 84, 88, 9, 90, 94,',
       '108, 79,', '102, 103, 104, 106, 107, 109, 110, 113, 114,',
       '104, 109,', '107, 109, 110, 111, 112, 114, 115,',
       '104, 107, 111,', '105, 107, 111,',
       '1, 10, 104, 107, 108, 110, 14, 17, 5, 6, 79, 84, 88, 90, 94,',
       '101, 102, 103, 104, 107, 109, 110, 114, 75,', '122,',
       '100, 102, 106,', '104, 107, 110, 112,', '120,',
       '102, 104, 106, 107, 108, 109, 110, 113, 114,',
       '102, 106, 109, 110,',
       '101, 102, 103, 104, 106, 107, 109, 110, 113, 114,', '113, 114,',
       '103, 114,', '102, 104, 106, 107, 109, 110, 113, 115,',
       '105, 106, 107, 109,', '104, 107, 109, 113,', '104, 105,',
       '115, 43, 78,', '103, 109, 111, 114,', '115, 23, 43, 78,',
       '104, 106, 107, 109, 114,', '102, 105,', '113, 115,',
       '102, 104, 105, 107, 108, 111, 112, 114, 68, 72, 75,',
       '115, 46, 62, 75,', '109, 114,', '110, 113,', '108, 109,',
       '104, 107, 109, 110, 114,', '103, 105, 107, 109, 110,', '08, 108,',
       '105, 109,', '105, 106, 113,', '106, 110,',
       '102, 103, 107, 110, 111, 112,', '102, 103, 107, 112,',
       '102, 104, 114,',
       '101, 102, 103, 104, 106, 107, 109, 110, 113, 114, 75,',
       '103, 107, 113,', '109, 111, 114,', '104, 105, 107, 109, 111,',
       '104, 108, 110, 75,', '101, 107, 110,', '101, 110, 113,',
       '101, 105,', '103, 104, 107, 109, 114,', '109, 115,', '100, 106,',
       '103, 105, 107,', '105, 116,', '101, 113,', '113, 116,',
       '110, 112, 115,', '116,'], dtype=object)

In [91]:
df_copy['event_agency'].unique()

array(['Parks Department', 'Street Activity Permit Office',
       'Police Department',
       "Mayor's Office of Film, Theatre & Broadcasting"], dtype=object)

In [92]:
df_copy = df_copy.drop(['event_id', 'event_agency', 'police_precinct', 'community_board'], axis = 1)

In [93]:
df_copy.columns

Index(['event_name', 'start_date_time', 'end_date_time', 'event_type',
       'event_borough', 'event_location', 'street_closure_type', 'time',
       'year'],
      dtype='object')

In [94]:
len(df_copy['event_name'].unique())

7061

In [95]:
df_copy['event_type'].unique()

array(['Sport - Youth', 'Special Event', 'Sport - Adult', 'Street Event',
       'Farmers Market', 'Block Party', 'Religious Event', 'Parade',
       'Open Street Partner Event', 'Single Block Festival',
       'Athletic Race / Tour', 'Sidewalk Sale', 'Plaza Event',
       'Production Event', 'Health Fair', 'Stationary Demonstration',
       'Open Culture', 'Rigging Permit', 'Plaza Partner Event',
       'Street Festival', 'Shooting Permit', 'Rally',
       'Athletic - Charitable', 'Open Street Event', 'BID Multi-Block',
       'Bike the Block', 'Press Conference'], dtype=object)

In [96]:
len(df_copy['event_type'].unique())

27

In [97]:
categories = {
    'Sports': ['Sport - Youth', 'Sport - Adult', 'Athletic Race / Tour', 'Athletic - Charitable', 'Bike the Block'],
    'Festivals': ['Single Block Festival', 'Street Festival'],
    'Commercial': ['Farmers Market', 'Block Party', 'Sidewalk Sale', 'BID Multi-Block'],
    'Health': ['Health Fair'],
    'Permits/Logistical': ['Shooting Permit', 'Rigging Permit', 'Production Event'],
    'Political/Press': ['Rally', 'Stationary Demonstration', 'Press Conference', 'Parade'],
    'Public Events': ['Open Culture', 'Plaza Event', 'Plaza Partner Event', 'Open Street Event'
                      , 'Open Street Partner Event'],
    'Religious': ['Religious Event'],
    'Other': ['Special Event', 'Street Event']
}

In [98]:
total_items = 0
for key in categories:
    total_items += len(categories[key])
print(total_items)

27

In [99]:
for category in categories.keys():
  df_copy[category] = [1 if x in categories[category] else 0 for x in df_copy['event_type']]

In [100]:
df_copy.columns

Index(['event_name', 'start_date_time', 'end_date_time', 'event_type',
       'event_borough', 'event_location', 'street_closure_type', 'time',
       'year', 'Sports', 'Festivals', 'Commercial', 'Health',
       'Permits/Logistical', 'Political/Press', 'Public Events', 'Religious',
       'Other'],
      dtype='object')

In [101]:
df_copy = df_copy.drop(['event_name', 'event_type'], axis = 1)

In [102]:
df_copy.columns

Index(['start_date_time', 'end_date_time', 'event_borough', 'event_location',
       'street_closure_type', 'time', 'year', 'Sports', 'Festivals',
       'Commercial', 'Health', 'Permits/Logistical', 'Political/Press',
       'Public Events', 'Religious', 'Other'],
      dtype='object')

In [103]:
df_copy['event_borough'].unique()

array(['Queens'], dtype=object)

In [104]:
df_copy = df_copy.drop('event_borough', axis = 1)

In [105]:
df_copy['event_location'].unique()

array(['Rockaway Beach Boardwalk: Football-01',
       'Cambria Playground/Cabbell Park: Lawn',
       'Cunningham Park: Picnic Green 2   ,Cunningham Park: Baseball-01 ,Cunningham Park: Baseball-05',
       ..., "Worlds Fair Playground: World's Fair Playground-Handball-05",
       'Chappetto Square: Volleyball-02',
       '90 AVENUE between 188 STREET and 189 STREET,  90 AVENUE between 188 STREET and 189 STREET,  90 AVENUE between 188 STREET and 193 STREET,  193 STREET between 90 AVENUE and JAMAICA AVENUE,  JAMAICA AVENUE between 193 STREET and 197 STREET,  90 AVENUE between 197 STREET and 205 STREET,  205 STREET between 89 AVENUE and 90 AVENUE,  89 AVENUE between 205 STREET and FRANCIS LEWIS BOULEVARD,  89 AVENUE between FRANCIS LEWIS BOULEVARD and 207 STREET,  89 AVENUE between FRANCIS LEWIS BOULEVARD and 207 STREET,  188 STREET between 91 AVENUE and 90 AVENUE,  197 STREET between JAMAICA AVENUE and 90 AVENUE'],
      dtype=object)

In [106]:
df_copy['street_closure_type'].unique()

array(['N/A', 'Curb Lane Only', 'Full Street Closure',
       'Sidewalk and Curb Lane Closure', 'Partial Sidewalk Closure',
       'Pedestrian Plaza', 'Sidewalk and Curb Lane Closure ',
       'Full Street Closure ', 'Full Sidewalk Closure ',
       'Pedestrian Plaza ', 'Partial Sidewalk Closure ',
       'Sidewalk and Street Closure ', 'Sidewalk and Street Closure',
       'Full Sidewalk Closure'], dtype=object)

In [107]:
df_copy['street_closure_type'].value_counts()

street_closure_type
N/A                                4026870
Full Street Closure                  18634
Curb Lane Only                       14704
Sidewalk and Curb Lane Closure       10085
Partial Sidewalk Closure              7320
Full Street Closure                   5922
Pedestrian Plaza                      2101
Sidewalk and Curb Lane Closure        1702
Partial Sidewalk Closure               879
Full Sidewalk Closure                  593
Pedestrian Plaza                       535
Full Sidewalk Closure                  332
Sidewalk and Street Closure            301
Sidewalk and Street Closure             46
Name: count, dtype: int64

In [108]:
df_copy.dtypes

start_date_time        datetime64[ns]
end_date_time          datetime64[ns]
event_location                 object
street_closure_type            object
time                   datetime64[ns]
year                            int32
Sports                          int64
Festivals                       int64
Commercial                      int64
Health                          int64
Permits/Logistical              int64
Political/Press                 int64
Public Events                   int64
Religious                       int64
Other                           int64
dtype: object

In [139]:
closures = ['Street', 'Curb Lane', 'Sidewalk', 'Partial Sidewalk', 'Pedestrian Plaza', 'N/A']

for clos in closures:
  df_copy[clos] = [1 if clos in str(x) else 0 for x in df_copy['street_closure_type']]
df_copy.columns

Index(['start_date_time', 'end_date_time', 'event_location',
       'street_closure_type', 'time', 'year', 'Sports', 'Festivals',
       'Commercial', 'Health', 'Permits/Logistical', 'Political/Press',
       'Public Events', 'Religious', 'Other', 'Street', 'Curb Lane',
       'Sidewalk', 'Partial Sidewalk', 'Pedestrian Plaza', 'N/A',
       'No Closure'],
      dtype='object')

In [140]:
df_copy['Sidewalk'] = [0 if x == 1 else y for x, y in zip(df_copy['Partial Sidewalk'], df_copy['Sidewalk'])]

In [141]:
df_copy['No Closure'] = df_copy['N/A']

In [142]:
for clos in closures:
  print(f"{clos}: {len(df_copy[df_copy[clos] == 1])}")

Street: 24903
Curb Lane: 26491
Sidewalk: 13059
Partial Sidewalk: 8199
Pedestrian Plaza: 2636
N/A: 4026870

In [143]:
df_copy['street_closure_type'].value_counts()

street_closure_type
N/A                                4026870
Full Street Closure                  18634
Curb Lane Only                       14704
Sidewalk and Curb Lane Closure       10085
Partial Sidewalk Closure              7320
Full Street Closure                   5922
Pedestrian Plaza                      2101
Sidewalk and Curb Lane Closure        1702
Partial Sidewalk Closure               879
Full Sidewalk Closure                  593
Pedestrian Plaza                       535
Full Sidewalk Closure                  332
Sidewalk and Street Closure            301
Sidewalk and Street Closure             46
Name: count, dtype: int64

In [144]:
df_copy[closures].value_counts()

Street  Curb Lane  Sidewalk  Partial Sidewalk  Pedestrian Plaza  N/A
0       0          0         0                 0                 1      4026870
1       0          0         0                 0                 0        24556
0       1          0         0                 0                 0        14704
                   1         0                 0                 0        11787
        0          0         1                 0                 0         8199
                             0                 1                 0         2636
                   1         0                 0                 0          925
1       0          1         0                 0                 0          347
Name: count, dtype: int64

In [145]:
df_copy.columns

Index(['start_date_time', 'end_date_time', 'event_location',
       'street_closure_type', 'time', 'year', 'Sports', 'Festivals',
       'Commercial', 'Health', 'Permits/Logistical', 'Political/Press',
       'Public Events', 'Religious', 'Other', 'Street', 'Curb Lane',
       'Sidewalk', 'Partial Sidewalk', 'Pedestrian Plaza', 'N/A',
       'No Closure'],
      dtype='object')

In [146]:
df_copy = df_copy.drop(['street_closure_type', 'N/A'], axis = 1)

In [147]:
df_copy

,start_date_time,end_date_time,event_location,time,year,Sports,Festivals,Commercial,Health,Permits/Logistical,Political/Press,Public Events,Religious,Other,Street,Curb Lane,Sidewalk,Partial Sidewalk,Pedestrian Plaza,No Closure
0,2024-09-14 08:00:00,2024-09-14 20:00:00,Rockaway Beach Boardwalk: Football-01,2024-09-14 08:00:00,2024,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,2024-10-05 12:00:00,2024-10-05 17:00:00,Cambria Playground/Cabbell Park: Lawn,2024-10-05 12:00:00,2024,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
2,2024-09-15 11:00:00,2024-09-15 16:00:00,"Cunningham Park: Picnic Green 2 ,Cunningham ...",2024-09-15 11:00:00,2024,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
3,2024-10-17 17:00:00,2024-10-17 20:00:00,Flushing Meadows Corona Park: Soccer-01,2024-10-17 17:00:00,2024,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,2024-09-24 15:30:00,2024-09-24 19:00:00,Kissena Corridor West: Captain Mario Fajardo P...,2024-09-24 15:30:00,2024,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4090019,2025-05-30 08:00:00,2025-05-30 13:00:00,Highland Park: Highland Park-Upper Highland Pl...,2025-05-30 08:00:00,2025,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
4090020,2025-05-01 08:00:00,2025-05-01 10:30:00,"Flushing Meadows Corona Park: Soccer-02 ,Flush...",2025-05-01 08:00:00,2025,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4090021,2025-05-02 16:00:00,2025-05-02 18:00:00,Cunningham Park: Baseball-05,2025-05-02 16:00:00,2025,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4090022,2025-04-21 13:00:00,2025-04-21 20:00:00,John Golden Park: Softball-04,2025-04-21 13:00:00,2025,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4090023,2025-04-27 13:00:00,2025-04-27 17:00:00,Baisley Pond Park: Cricket-05,2025-04-27 13:00:00,2025,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1